In [2]:
"""
preprocessing.py
Cleans and prepares the VCT player stats dataset for the Autoencoder pipeline.
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
def load_data():
    df = pd.read_csv(r'C:\Users\User\Downloads\valorant vct players real.csv')
    return df

In [10]:
def clean_data(df):
    percent_cols = ["KAST", "Opening Duel Win %"]
    for col in percent_cols:
        if df[col].dtype == object:
            df[col] = df[col].str.replace("%", "", regex=False).astype(float)
    df = df.dropna()
    return df

In [11]:
def select_features(df):
    feature_cols = [
        "ACS", "K:D", "KAST", "ADR", "KPR", "APR",
        "FKPR", "FDPR", "HS%", "CL%", "Opening Duel Win %"
    ]
    return df[feature_cols], df[["Player", "Team", "Region"]]

In [12]:
def scale_features(X):
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    return X_scaled, scaler

In [13]:
df = load_data()
df = clean_data(df)
X, meta = select_features(df)
X_scaled, scaler = scale_features(X)
print("Data shape after preprocessing:", X_scaled.shape)
meta.head()

Data shape after preprocessing: (121, 11)

      Player        Team         Region
0       leaf      Cloud9  North America
1  Cryocells        XSET  North America
2       cNed       Acend           EMEA
3      AYRIN        XSET  North America
4     nukkye  G2 Esports           EMEA

In [14]:
pd.DataFrame(X_scaled, columns=X.columns).head()

,ACS,K:D,KAST,ADR,KPR,APR,FKPR,FDPR,HS%,CL%,Opening Duel Win %
0,2.526106,1.839264,-0.057839,2.493459,2.474961,-0.791926,2.415452,1.810026,-0.308339,2.143896,0.839748
1,2.127125,2.905301,-0.317041,1.600983,2.795708,-2.154984,1.772158,1.031543,0.122979,0.284316,0.978181
2,2.366514,1.463016,-0.576243,2.073090,2.261130,-1.609761,1.986590,-0.265928,-0.308339,-1.575264,2.120250
3,-1.304105,-1.170723,0.460566,-1.561485,-1.480912,1.252662,-0.801016,-0.784916,-2.680591,-0.180579,-0.221569
4,2.326616,1.776556,1.756577,2.758614,1.619637,0.571133,0.700003,-0.006434,-1.170976,-0.025614,0.932037